import os
from flask import Flask, render_template, jsonify

app = Flask(__name__)

MANUAL_FILENAME_FIXES = {
    "Unduriusy": "undurisy.png",
    "Vengur": "vengur.png",
    "Remigesy": "remigesy.png",
    "Oko": "oko.png",
    "Dar Skrzydlatej": "dar_skrzydlatej.png",
    "Nurthil": "nurthil.png",
    "Latarnia Życia": "Latarnia_życia.png",
    "Żmij": "Żmij.png",
    "Allenor": "Allenor.png",
    "Attawa": "Attawa.png",
    "Gorthdar": "Gorthdar.png",
    "Imisindo": "Imisindo.png",
    "Washi": "Washi.png"
}


# DODAJ TO NA GÓRZE app.py (pod MANUAL_FILENAME_FIXES)
# Cache plików, żeby nie męczyć dysku w pętli
CACHED_FILES = {
    'epik': os.listdir(os.path.join(app.root_path, 'static', 'epik')) if os.path.exists(os.path.join(app.root_path, 'static', 'epik')) else [],
    'rary': os.listdir(os.path.join(app.root_path, 'static', 'rary')) if os.path.exists(os.path.join(app.root_path, 'static', 'rary')) else []
}

def find_image_file(item_name):
    # 1. Sprawdź ręczne poprawki
    if item_name in MANUAL_FILENAME_FIXES:
        fname = MANUAL_FILENAME_FIXES[item_name]
        for folder in ['epik', 'rary']:
            if fname in CACHED_FILES[folder]:
                return fname, folder
        return fname, "rary"

    # 2. Szukaj automatycznie w pamięci (nie na dysku!)
    target = item_name.lower().replace(" ", "").replace("'", "").replace("-", "")
    for folder in ['epik', 'rary']:
        for filename in CACHED_FILES[folder]:
            name_no_ext = os.path.splitext(filename)[0]
            cleaned_file = name_no_ext.lower().replace(" ", "").replace("_", "").replace("'", "").replace("-", "")
            if target == cleaned_file or (len(target) > 3 and target in cleaned_file):
                return filename, folder
    return "default.png", "rary"

ITEMS_DB = {
    "Derengil": {"rank": 2, "cap": 4, "slots": 1, "type": "Miecz", "stats": {"Waga": "2", "Wartość": "36 000 złota", "Wymagany poziom": "18", "Wymagana siła": "20", "Obrażenia": "66", "Typ obrażeń": "Sieczne", "Siła": "+8", "Zręczność": "+6", "Kondycja": "+40"}},
    "Maiarot": {"rank": 2, "cap": 4, "slots": 1, "type": "Naszyjnik", "stats": {"Waga": "3", "Wartość": "36 000 złota", "Wymagany poziom": "18", "PŻ": "+120", "Odporność uroki": "+20"}},
    "Sturprang": {"rank": 2, "cap": 4, "slots": 1, "type": "Kije", "stats": {"Waga": "2", "Wartość": "36 000 złota", "Wymagany poziom": "18", "Wymagana moc": "20", "Obrażenia": "71", "Typ obrażeń": "Obuchowe", "Moc": "+8", "Wiedza": "+6", "Mana": "+40"}},
    "Arcanscape": {"rank": 2, "cap": 4, "slots": 1, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "40 000 złota", "Wymagany poziom": "20", "PŻ": "+70", "Mana": "+20", "Kondycja": "+20", "Odporność uroki": "+30"}},
    "Ayol": {"rank": 2, "cap": 4, "slots": 1, "type": "Łuk", "stats": {"Waga": "15", "Wartość": "40 000 złota", "Wymagany poziom": "20", "Wymagana zręczność": "20", "Obrażenia": "74", "Typ obrażeń": "Kłute", "Siła": "+5", "Zręczność": "+9", "Kondycja": "+60"}},
    "Martumal": {"rank": 2, "cap": 4, "slots": 1, "type": "Hełm", "stats": {"Waga": "15", "Wartość": "40 000 złota", "Wymagany poziom": "20", "Wymagana moc": "20", "Moc": "+6", "Wiedza": "+4", "Mana": "+40", "Pancerz sieczne": "+19", "Pancerz obuchowe": "+20", "Pancerz kłute": "+21", "Odporność uroki": "+20"}},
    "Anabolik": {"rank": 2, "cap": 4, "slots": 1, "type": "Pas", "stats": {"Waga": "10", "Wartość": "72 000 złota", "Wymagany poziom": "24", "Wymagana siła": "25", "Siła": "+8", "Zręczność": "+5", "PŻ": "+110"}},
    "Bartaur": {"rank": 2, "cap": 4, "slots": 1, "type": "Zbroja", "stats": {"Waga": "15", "Wartość": "72 000 złota", "Wymagany poziom": "24", "Wymagana wiedza": "25", "Moc": "+5", "Wiedza": "+8", "Mana": "+50", "Pancerz sieczne": "+25", "Pancerz obuchowe": "+25", "Pancerz kłute": "+25"}},
    "Tasak": {"rank": 2, "cap": 4, "slots": 1, "type": "Topór dwuręczny", "stats": {"Waga": "40", "Wartość": "56 000 złota", "Wymagany poziom": "22", "Wymagana siła": "25", "Obrażenia": "83", "Typ obrażeń": "Sieczne", "Siła": "+13", "PŻ": "+30", "Kondycja": "+60"}},
    "Basileus": {"rank": 3, "cap": 4, "slots": 1, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "104 000 złota", "Wymagany poziom": "28", "Wymagana moc": "30", "Moc": "+9", "Wiedza": "+7", "Odporność zimno": "+20", "Odporność uroki": "+20"}},
    "Fraxy": {"rank": 3, "cap": 4, "slots": 1, "type": "Rękawice", "stats": {"Waga": "8", "Wartość": "120 000 złota", "Wymagany poziom": "30", "Wymagana moc": "30", "Moc": "+5", "Wiedza": "+13", "PŻ": "+50", "Mana": "+40", "Odporność uroki": "+10"}},
    "Grzebień": {"rank": 3, "cap": 4, "slots": 1, "type": "Hełm", "stats": {"Waga": "15", "Wartość": "120 000 złota", "Wymagany poziom": "30", "Wymagana siła": "30", "Siła": "+8", "Zręczność": "+4", "PŻ": "+20", "Kondycja": "+40", "Pancerz sieczne": "+23", "Pancerz obuchowe": "+24", "Pancerz kłute": "+28", "Odporność uroki": "+20"}},
    "Moczary": {"rank": 3, "cap": 4, "slots": 1, "type": "Buty", "stats": {"Waga": "10", "Wartość": "120 000 złota", "Wymagany poziom": "30", "Wymagana siła": "30", "Siła": "+5", "Zręczność": "+3", "PŻ": "+30", "Pancerz sieczne": "+23", "Pancerz obuchowe": "+22", "Pancerz kłute": "+25"}},
    "Czengsvesy": {"rank": 2, "cap": 4, "slots": 1, "type": "Buty", "stats": {"Waga": "8", "Wartość": "72 000 złota", "Wymagany poziom": "24", "Wymagana wiedza": "25", "Moc": "+7", "Wiedza": "+10", "Mana": "+30", "Pancerz sieczne": "+23", "Pancerz obuchowe": "+22", "Pancerz kłute": "+25"}},
    "Fiskorl": {"rank": 3, "cap": 4, "slots": 1, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "104 000 złota", "Wymagany poziom": "28", "Wymagana siła": "25", "Siła": "+9", "Zręczność": "+7", "Odporność zimno": "+20", "Odporność uroki": "+20"}},
    "Rolrak": {"rank": 2, "cap": 4, "slots": 1, "type": "Kastety", "stats": {"Waga": "5", "Wartość": "72 000 złota", "Wymagany poziom": "24", "Wymagana zręczność": "25", "Obrażenia": "81", "Typ obrażeń": "Sieczne", "Siła": "+6", "Zręczność": "+8", "Kondycja": "+40", "Odporność uroki": "+20"}},
    "Davgretor": {"rank": 3, "cap": 4, "slots": 1, "type": "Młot dwuręczny", "stats": {"Waga": "35", "Wartość": "136 000 złota", "Wymagany poziom": "32", "Wymagana siła": "30", "Obrażenia": "103", "Typ obrażeń": "Obuchowe", "Siła": "+15", "Zręczność": "+2", "PŻ": "+100", "Kondycja": "+50"}},
    "Geomorph Core": {"rank": 3, "cap": 4, "slots": 1, "type": "Kije", "stats": {"Waga": "15", "Wartość": "136 000 złota", "Wymagany poziom": "32", "Wymagana moc": "30", "Obrażenia": "95", "Typ obrażeń": "Obuchowe", "Moc": "+15", "Wiedza": "+2", "Mana": "+150"}},
    "Markahn": {"rank": 3, "cap": 4, "slots": 1, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "136 000 złota", "Wymagany poziom": "32", "Zręczność": "+3", "Wiedza": "+3", "PŻ": "+70", "Mana": "+20", "Kondycja": "+20", "Odporność ogień": "+30", "Odporność uroki": "+30"}},
    "Brassary": {"rank": 3, "cap": 4, "slots": 1, "type": "Rękawice", "stats": {"Waga": "6", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana moc": "35", "Moc": "+10", "Wiedza": "+5", "PŻ": "+10", "Mana": "+60", "Odporność ogień": "+20", "Odporność uroki": "+20"}},
    "Piroklast": {"rank": 3, "cap": 4, "slots": 1, "type": "Łuk", "stats": {"Waga": "15", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana zręczność": "35", "Obrażenia": "98", "Typ obrażeń": "Kłute", "Siła": "+2", "Zręczność": "+9", "PŻ": "+80", "Kondycja": "+60", "Odporność ogień": "+20", "Odporność zimno": "+10"}},
    "Uguns": {"rank": 3, "cap": 4, "slots": 1, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "152 000 złota", "Wymagany poziom": "34", "PŻ": "+140", "Mana": "+40", "Kondycja": "+40", "Odporność ogień": "+20", "Odporność uroki": "+20"}},
    "Fulgur": {"rank": 3, "cap": 4, "slots": 1, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana moc": "35", "Moc": "+9", "Wiedza": "+8", "PŻ": "+40", "Mana": "+10", "Odporność energia": "+20", "Odporność uroki": "+20"}},
    "Radius electricum": {"rank": 3, "cap": 4, "slots": 1, "type": "Pas", "stats": {"Waga": "1", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana moc": "35", "Moc": "+9", "Wiedza": "+6", "Mana": "+70", "Odporność energia": "+40"}},
    "Sphaera": {"rank": 3, "cap": 4, "slots": 1, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana siła": "35", "Siła": "+8", "Zręczność": "+6", "Kondycja": "+80", "Odporność energia": "+40"}},
    "Ishelm": {"rank": 3, "cap": 4, "slots": 1, "type": "Hełm", "stats": {"Waga": "12", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana zręczność": "35", "Siła": "+6", "Zręczność": "+10", "PŻ": "+30", "Kondycja": "+10", "Pancerz sieczne": "+29", "Pancerz obuchowe": "+33", "Pancerz kłute": "+33"}},
    "Isthrimm": {"rank": 3, "cap": 4, "slots": 1, "type": "Tarcza", "stats": {"Waga": "40", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana klasa": "Rycerz", "PŻ": "+80", "Kondycja": "+60", "Pancerz sieczne": "+31", "Pancerz obuchowe": "+30", "Pancerz kłute": "+30", "Odporność ogień": "+25"}},
    "Isverd": {"rank": 3, "cap": 4, "slots": 1, "type": "Miecz", "stats": {"Waga": "15", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Obrażenia": "90", "Typ obrażeń": "Sieczne", "PŻ": "+120", "Mana": "+20", "Kondycja": "+110", "Odporność ogień": "+10", "Odporność zimno": "+20"}},
    "Karlder": {"rank": 3, "cap": 4, "slots": 1, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana siła": "35", "Siła": "+9", "Zręczność": "+8", "PŻ": "+40", "Kondycja": "+10", "Odporność energia": "+20", "Odporność uroki": "+20"}},
    "Khalam": {"rank": 3, "cap": 4, "slots": 1, "type": "Hełm", "stats": {"Waga": "8", "Wartość": "136 000 złota", "Wymagany poziom": "32", "Wymagana wiedza": "35", "Moc": "+6", "Wiedza": "+8", "Mana": "+60", "Pancerz sieczne": "+25", "Pancerz obuchowe": "+25", "Pancerz kłute": "+25", "Odporność uroki": "+20"}},
    "Tężec": {"rank": 3, "cap": 4, "slots": 1, "type": "Kije", "stats": {"Waga": "5", "Wartość": "136 000 złota", "Wymagany poziom": "32", "Wymagana wiedza": "35", "Obrażenia": "95", "Typ obrażeń": "Kłute", "Moc": "+4", "Wiedza": "+9", "PŻ": "+90", "Mana": "+40", "Odporność uroki": "+20"}},
    "Brunnle": {"rank": 3, "cap": 4, "slots": 1, "type": "Zbroja", "stats": {"Waga": "30", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana siła": "35", "Siła": "+7", "Zręczność": "+5", "PŻ": "+60", "Kondycja": "+40", "Pancerz sieczne": "+29", "Pancerz obuchowe": "+31", "Pancerz kłute": "+29"}},
    "Lysmary": {"rank": 3, "cap": 4, "slots": 1, "type": "Buty", "stats": {"Waga": "6", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana moc": "35", "Moc": "+8", "Wiedza": "+2", "PŻ": "+80", "Mana": "+60", "Pancerz sieczne": "+29", "Pancerz obuchowe": "+27", "Pancerz kłute": "+29"}},
    "Sidun": {"rank": 3, "cap": 4, "slots": 1, "type": "Miecz dwuręczny", "stats": {"Waga": "20", "Wartość": "152 000 złota", "Wymagany poziom": "34", "Wymagana siła": "35", "Obrażenia": "107", "Typ obrażeń": "Sieczne", "Siła": "+19", "PŻ": "+100", "Kondycja": "+50"}},
    "Gest Władcy": {"rank": 3, "cap": 4, "slots": 1, "type": "Rękawice", "stats": {"Waga": "8", "Wartość": "136 000 złota", "Wymagany poziom": "32", "Wymagana siła": "35", "Siła": "+12", "Zręczność": "+8", "PŻ": "+60", "Mana": "+20", "Kondycja": "+40"}},
    "Koriatula": {"rank": 3, "cap": 4, "slots": 1, "type": "Pas", "stats": {"Waga": "10", "Wartość": "160 000 złota", "Wymagany poziom": "35", "Wymagana wiedza": "35", "Moc": "+8", "Wiedza": "+15", "PŻ": "+80", "Mana": "+20", "Kondycja": "+20"}},
    "Obroża Władcy": {"rank": 3, "cap": 4, "slots": 1, "type": "Naszyjnik", "stats": {"Waga": "6", "Wartość": "160 000 złota", "Wymagany poziom": "35", "Wymagana moc": "35", "Moc": "+14", "Wiedza": "+13", "PŻ": "+80"}},
    "Promuris": {"rank": 3, "cap": 4, "slots": 1, "type": "Pas", "stats": {"Waga": "10", "Wartość": "160 000 złota", "Wymagany poziom": "35", "Wymagana siła": "35", "Siła": "+15", "Zręczność": "+14", "PŻ": "+60"}},
    "Irkamale": {"rank": 3, "cap": 4, "slots": 1, "type": "Kastety", "stats": {"Waga": "6", "Wartość": "160 000 złota", "Wymagany poziom": "35", "Wymagana zręczność": "35", "Obrażenia": "100", "Typ obrażeń": "Obuchowe", "Siła": "+4", "Zręczność": "+7", "PŻ": "+120", "Mana": "+40", "Kondycja": "+80"}},
    "Jeroszki": {"rank": 3, "cap": 4, "slots": 1, "type": "Buty", "stats": {"Waga": "15", "Wartość": "160 000 złota", "Wymagany poziom": "35", "PŻ": "+100", "Mana": "+20", "Kondycja": "+100", "Pancerz sieczne": "+26", "Pancerz obuchowe": "+26", "Pancerz kłute": "+26", "Odporność ogień": "+20"}},
    "Ostolbin": {"rank": 3, "cap": 4, "slots": 1, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "160 000 złota", "Wymagany poziom": "35", "Wymagana moc": "35", "Moc": "+6", "Wiedza": "+5", "PŻ": "+120", "Mana": "+120"}},
    "Caratris": {"rank": 4, "cap": 8, "slots": 2, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "450 000 złota", "Wymagany poziom": "45", "PŻ": "+30", "Odporność ogień": "+35", "Odporność zimno": "+35", "Odporność energia": "+35", "Odporność uroki": "+35"}},
    "Smocze Skrzydło": {"rank": 4, "cap": 8, "slots": 2, "type": "Tarcza", "stats": {"Waga": "30", "Wartość": "450 000 złota", "Wymagany poziom": "45", "Wymagana siła": "45", "Wymagana klasa": "Rycerz", "Siła": "+4", "Zręczność": "+6", "PŻ": "+100", "Kondycja": "+60", "Pancerz sieczne": "+36", "Pancerz obuchowe": "+36", "Pancerz kłute": "+36"}},
    "Smoczy Gnat": {"rank": 4, "cap": 8, "slots": 2, "type": "Kije", "stats": {"Waga": "15", "Wartość": "450 000 złota", "Wymagany poziom": "45", "Wymagana moc": "45", "Obrażenia": "117", "Typ obrażeń": "Obuchowe", "Moc": "+20", "Wiedza": "+4", "PŻ": "+70", "Mana": "+140"}},
    "Balast": {"rank": 4, "cap": 8, "slots": 2, "type": "Pierścień", "stats": {"Waga": "3", "Wartość": "450 000 złota", "Wymagany poziom": "45", "PŻ": "+250", "Mana": "+40", "Kondycja": "+40", "Odporność ogień": "+10", "Odporność zimno": "+10", "Odporność energia": "+10", "Odporność uroki": "+10"}},
    "Bryza": {"rank": 4, "cap": 8, "slots": 2, "type": "Peleryna", "stats": {"Waga": "15", "Wartość": "450 000 złota", "Wymagany poziom": "45", "Wymagana zręczność": "45", "Siła": "+7", "Zręczność": "+9", "PŻ": "+200", "Mana": "+30", "Kondycja": "+60"}},
    "Navigon": {"rank": 4, "cap": 8, "slots": 2, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "450 000 złota", "Wymagany poziom": "45", "Wymagana wiedza": "45", "Moc": "+12", "Wiedza": "+20", "PŻ": "+80", "Mana": "+50"}},
    "Nit": {"rank": 4, "cap": 8, "slots": 2, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "450 000 złota", "Wymagany poziom": "45", "Wymagana zręczność": "45", "Siła": "+12", "Zręczność": "+20", "PŻ": "+80", "Kondycja": "+50"}},
    "Pancerz Komandorski": {"rank": 4, "cap": 8, "slots": 2, "type": "Zbroja", "stats": {"Waga": "22", "Wartość": "450 000 złota", "Wymagany poziom": "45", "Wymagana wiedza": "45", "Moc": "+8", "Wiedza": "+12", "PŻ": "+60", "Mana": "+80", "Kondycja": "+30", "Pancerz sieczne": "+26", "Pancerz obuchowe": "+28", "Pancerz kłute": "+26"}},
    "Gathril": {"rank": 5, "cap": 10, "slots": 2, "type": "Hełm", "stats": {"Waga": "12", "Wartość": "950 000 złota", "Wymagany poziom": "55", "PŻ": "+140", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+38", "Pancerz kłute": "+37", "Odporność ogień": "+20", "Odporność zimno": "+20", "Odporność energia": "+20", "Odporność uroki": "+10"}},
    "Nurthil": {"rank": 5, "cap": 10, "slots": 2, "type": "Peleryna", "stats": {"Waga": "15", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana moc": "55", "Moc": "+39", "Wiedza": "+24", "PŻ": "-90", "Mana": "-50", "Odporność ogień": "+20"}},
    "Tirhel": {"rank": 5, "cap": 10, "slots": 2, "type": "Spodnie", "stats": {"Waga": "20", "Wartość": "950 000 złota", "Wymagany poziom": "55", "PŻ": "+140", "Pancerz sieczne": "+37", "Pancerz obuchowe": "+35", "Pancerz kłute": "+38", "Odporność ogień": "+20", "Odporność zimno": "+20", "Odporność energia": "+20", "Odporność uroki": "+10"}},
    "Virthil": {"rank": 5, "cap": 10, "slots": 2, "type": "Zbroja", "stats": {"Waga": "40", "Wartość": "950 000 złota", "Wymagany poziom": "55", "PŻ": "+140", "Pancerz sieczne": "+38", "Pancerz obuchowe": "+37", "Pancerz kłute": "+35", "Odporność ogień": "+20", "Odporność zimno": "+20", "Odporność energia": "+20", "Odporność uroki": "+10"}},
    "Danthum": {"rank": 5, "cap": 10, "slots": 2, "type": "Naszyjnik", "stats": {"Waga": "3", "Wartość": "700 000 złota", "Wymagany poziom": "50", "Wymagana zręczność": "50", "Siła": "+9", "Zręczność": "+26", "PŻ": "+50", "Kondycja": "+100"}},
    "Pressory": {"rank": 5, "cap": 10, "slots": 2, "type": "Rękawice", "stats": {"Waga": "12", "Wartość": "700 000 złota", "Wymagany poziom": "50", "Siła": "+15", "Zręczność": "+8", "PŻ": "+100", "Kondycja": "+100", "Odporność uroki": "+25"}},
    "Tangnary": {"rank": 5, "cap": 10, "slots": 2, "type": "Buty", "stats": {"Waga": "12", "Wartość": "700 000 złota", "Wymagany poziom": "50", "Wymagana zręczność": "50", "Siła": "+11", "Zręczność": "+13", "PŻ": "+50", "Kondycja": "+30", "Pancerz sieczne": "+33", "Pancerz obuchowe": "+27", "Pancerz kłute": "+33", "Odporność energia": "+15"}},
    "Valazan": {"rank": 5, "cap": 10, "slots": 2, "type": "Naszyjnik", "stats": {"Waga": "3", "Wartość": "700 000 złota", "Wymagany poziom": "50", "Wymagana wiedza": "50", "Moc": "+9", "Wiedza": "+26", "PŻ": "+50", "Mana": "+100"}},
    "Berglisy": {"rank": 5, "cap": 10, "slots": 2, "type": "Karwasze", "stats": {"Waga": "5", "Wartość": "1 200 000 złota", "Wymagany poziom": "60", "Wymagana wiedza": "60", "Moc": "+12", "Wiedza": "+18", "PŻ": "+240", "Mana": "+60"}},
    "Czacha": {"rank": 5, "cap": 10, "slots": 2, "type": "Hełm", "stats": {"Waga": "20", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana moc": "55", "Moc": "+18", "Wiedza": "+14", "PŻ": "+130", "Mana": "+40", "Pancerz sieczne": "+25", "Pancerz obuchowe": "+25", "Pancerz kłute": "+25"}},
    "Diabolo": {"rank": 5, "cap": 10, "slots": 2, "type": "Zbroja", "stats": {"Waga": "15", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana moc": "55", "Moc": "+28", "Wiedza": "-9", "PŻ": "+150", "Mana": "+150", "Pancerz sieczne": "+25", "Pancerz obuchowe": "+25", "Pancerz kłute": "+25"}},
    "Wzorek": {"rank": 5, "cap": 10, "slots": 2, "type": "Spodnie", "stats": {"Waga": "20", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana wiedza": "55", "Moc": "+4", "Wiedza": "+20", "PŻ": "+140", "Mana": "+110", "Pancerz sieczne": "+25", "Pancerz obuchowe": "+25", "Pancerz kłute": "+25"}},
    "Geury": {"rank": 5, "cap": 10, "slots": 2, "type": "Karwasze", "stats": {"Waga": "5", "Wartość": "1 200 000 złota", "Wymagany poziom": "60", "Wymagana zręczność": "60", "Siła": "+12", "Zręczność": "+18", "PŻ": "+240", "Kondycja": "+60"}},
    "Obdartusy": {"rank": 5, "cap": 10, "slots": 2, "type": "Spodnie", "stats": {"Waga": "20", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana siła": "55", "Siła": "+14", "Zręczność": "+10", "PŻ": "+130", "Pancerz sieczne": "+36", "Pancerz obuchowe": "+32", "Pancerz kłute": "+37"}},
    "Ognisty Młot": {"rank": 5, "cap": 10, "slots": 2, "type": "Młot dwuręczny", "stats": {"Waga": "30", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana siła": "55", "Obrażenia": "148", "Typ obrażeń": "Obuchowe", "Siła": "+28", "Zręczność": "+10", "PŻ": "+120", "Kondycja": "+50"}},
    "Opoka bogów": {"rank": 5, "cap": 10, "slots": 2, "type": "Zbroja", "stats": {"Waga": "15", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana siła": "55", "Siła": "+10", "Zręczność": "+9", "PŻ": "+120", "Kondycja": "+120", "Pancerz sieczne": "+28", "Pancerz obuchowe": "+29", "Pancerz kłute": "+33"}},
    "Sentrion": {"rank": 5, "cap": 10, "slots": 2, "type": "Pas", "stats": {"Waga": "15", "Wartość": "1 200 000 złota", "Wymagany poziom": "60", "Wymagana wiedza": "60", "Moc": "-5", "Wiedza": "+30", "PŻ": "+150", "Mana": "+110", "Odporność zimno": "+30"}},
    "Urntsul": {"rank": 6, "cap": 12, "slots": 2, "type": "Kije", "stats": {"Waga": "4", "Wartość": "1 500 000 złota", "Wymagany poziom": "63", "Wymagana moc": "60", "Obrażenia": "148", "Typ obrażeń": "Sieczne", "Moc": "+14", "Wiedza": "+10", "PŻ": "+290", "Mana": "+100"}},
    "Vaekany": {"rank": 5, "cap": 10, "slots": 2, "type": "Rękawice", "stats": {"Waga": "15", "Wartość": "1 200 000 złota", "Wymagany poziom": "60", "Wymagana moc": "60", "Moc": "+14", "Wiedza": "+13", "PŻ": "+20", "Mana": "+310"}},
    "Virral": {"rank": 6, "cap": 12, "slots": 2, "type": "Łuk", "stats": {"Waga": "15", "Wartość": "1 500 000 złota", "Wymagany poziom": "63", "Wymagana zręczność": "60", "Obrażenia": "148", "Typ obrażeń": "Kłute", "Siła": "+15", "Zręczność": "+25", "PŻ": "+100", "Mana": "+30", "Kondycja": "+100"}},
    "Xenothor": {"rank": 5, "cap": 10, "slots": 2, "type": "Peleryna", "stats": {"Waga": "15", "Wartość": "1 200 000 złota", "Wymagany poziom": "60", "Wymagana siła": "60", "Siła": "+39", "Zręczność": "+24", "PŻ": "-40", "Kondycja": "-50", "Odporność ogień": "+20"}},
    "Biltabandury": {"rank": 6, "cap": 12, "slots": 2, "type": "Rękawice", "stats": {"Waga": "10", "Wartość": "1 700 000 złota", "Wymagany poziom": "65", "Wymagana zręczność": "65", "Zręczność": "+20", "PŻ": "+200", "Mana": "+80", "Kondycja": "+80", "Odporność zimno": "+30"}},
    "Debba": {"rank": 6, "cap": 12, "slots": 2, "type": "Peleryna", "stats": {"Waga": "10", "Wartość": "1 700 000 złota", "Wymagany poziom": "65", "Wymagana zręczność": "65", "Zręczność": "+20", "PŻ": "+250", "Mana": "+40", "Kondycja": "+40", "Odporność zimno": "+40"}},
    "Ghaitarog": {"rank": 6, "cap": 12, "slots": 2, "type": "Hełm", "stats": {"Waga": "15", "Wartość": "1 700 000 złota", "Wymagany poziom": "65", "Wymagana zręczność": "65", "Siła": "+7", "Zręczność": "+9", "PŻ": "+120", "Kondycja": "+100", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+35", "Pancerz kłute": "+35", "Odporność zimno": "+30"}},
    "Oko": {"rank": 5, "cap": 10, "slots": 2, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "1 200 000 złota", "Wymagany poziom": "60", "PŻ": "+160", "Mana": "+70", "Kondycja": "+70", "Odporność ogień": "+25", "Odporność zimno": "+25", "Odporność energia": "+25", "Odporność uroki": "+25"}},
    "Drakhgard": {"rank": 5, "cap": 10, "slots": 2, "type": "Tarcza", "stats": {"Waga": "30", "Wartość": "1 200 000 złota", "Wymagany poziom": "60", "Wymagana klasa": "Rycerz", "Wymagana zręczność": "60", "PŻ": "+150", "Mana": "+40", "Kondycja": "+50", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+35", "Pancerz kłute": "+35", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Łamacz Woli": {"rank": 5, "cap": 10, "slots": 2, "type": "Młot", "stats": {"Waga": "20", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana zręczność": "55", "Obrażenia": "121", "Typ obrażeń": "Obuchowe", "Siła": "+8", "Zręczność": "+23", "PŻ": "+70", "Kondycja": "+170"}},
    "Ślady Zdarzeń": {"rank": 5, "cap": 10, "slots": 2, "type": "Buty", "stats": {"Waga": "15", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana wiedza": "55", "Moc": "+11", "Wiedza": "+15", "PŻ": "+120", "Mana": "+20", "Pancerz sieczne": "+25", "Pancerz obuchowe": "+25", "Pancerz kłute": "+25", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Wstęga Heurokratosa": {"rank": 5, "cap": 10, "slots": 2, "type": "Pas", "stats": {"Waga": "12", "Wartość": "950 000 złota", "Wymagany poziom": "55", "Wymagana zręczność": "55", "Siła": "+12", "Zręczność": "+20", "PŻ": "+80", "Kondycja": "+60", "Odporność ogień": "+15", "Odporność uroki": "+15"}},
    "Nadzieja Pokoleń": {"rank": 7, "cap": 15, "slots": 2, "type": "Zbroja", "stats": {"Waga": "18", "Wartość": "3 200 000 złota", "Wymagany poziom": "80", "Wymagana wiedza": "80", "Moc": "+13", "Wiedza": "+20", "PŻ": "+120", "Mana": "+60", "Kondycja": "+10", "Pancerz sieczne": "+33", "Pancerz obuchowe": "+35", "Pancerz kłute": "+32", "Odporność ogień": "+20", "Odporność energia": "+20"}},
    "Powrót Ivravula": {"rank": 7, "cap": 15, "slots": 2, "type": "Peleryna", "stats": {"Waga": "12", "Wartość": "3 200 000 złota", "Wymagany poziom": "80", "Wymagana zręczność": "80", "Siła": "+14", "Zręczność": "+24", "PŻ": "+100", "Mana": "+80", "Kondycja": "+120", "Odporność ogień": "+20", "Odporność energia": "+20"}},
    "Władca losu": {"rank": 7, "cap": 15, "slots": 2, "type": "Kije", "stats": {"Waga": "17", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana moc": "75", "Obrażenia": "179", "Typ obrażeń": "Obuchowe", "Moc": "+37", "Wiedza": "+20", "PŻ": "+80", "Mana": "+50", "Kondycja": "+50"}},
    "Zemsta Ivravula": {"rank": 7, "cap": 12, "slots": 2, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "2 200 000 złota", "Wymagany poziom": "70", "PŻ": "+500", "Mana": "+40", "Kondycja": "+40", "Odporność ogień": "+10", "Odporność zimno": "+10", "Odporność energia": "+10", "Odporność uroki": "+10"}},
    "Buoriany": {"rank": 6, "cap": 12, "slots": 2, "type": "Kastety", "stats": {"Waga": "20", "Wartość": "2 200 000 złota", "Wymagany poziom": "70", "Wymagana siła": "70", "Obrażenia": "160", "Typ obrażeń": "Sieczne", "Siła": "+34", "Zręczność": "+14", "PŻ": "+100", "Mana": "+50", "Kondycja": "+70"}},
    "Dagorilm": {"rank": 6, "cap": 12, "slots": 2, "type": "Pas", "stats": {"Waga": "15", "Wartość": "2 200 000 złota", "Wymagany poziom": "70", "Wymagana siła": "70", "Siła": "+24", "Zręczność": "+21", "PŻ": "+150", "Mana": "+20", "Kondycja": "+80"}},
    "Lawina": {"rank": 6, "cap": 12, "slots": 2, "type": "Młot", "stats": {"Waga": "30", "Wartość": "2 200 000 złota", "Wymagany poziom": "70", "Wymagana siła": "70", "Obrażenia": "143", "Typ obrażeń": "Obuchowe", "Siła": "+30", "Zręczność": "+20", "PŻ": "+150", "Mana": "+20", "Kondycja": "+30"}},
    "Thorimmy": {"rank": 6, "cap": 12, "slots": 2, "type": "Buty", "stats": {"Waga": "15", "Wartość": "2 200 000 złota", "Wymagany poziom": "70", "Wymagana wiedza": "70", "Moc": "+9", "Wiedza": "+20", "PŻ": "+160", "Mana": "+40", "Pancerz sieczne": "+30", "Pancerz obuchowe": "+30", "Pancerz kłute": "+30", "Odporność zimno": "+30"}},
    "Dracorporis": {"rank": 7, "cap": 15, "slots": 2, "type": "Peleryna", "stats": {"Waga": "15", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana moc": "75", "Moc": "+38", "Wiedza": "+22", "PŻ": "+90", "Mana": "+60"}},
    "Istav": {"rank": 7, "cap": 15, "slots": 2, "type": "Kije", "stats": {"Waga": "20", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana wiedza": "75", "Obrażenia": "169", "Typ obrażeń": "Obuchowe", "Moc": "+7", "Wiedza": "+30", "PŻ": "+130", "Mana": "+130", "Odporność zimno": "+20", "Odporność uroki": "+20"}},
    "Varrvy": {"rank": 7, "cap": 15, "slots": 2, "type": "Spodnie", "stats": {"Waga": "40", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana siła": "75", "Siła": "+31", "Zręczność": "+14", "PŻ": "+50", "Kondycja": "+30", "Pancerz sieczne": "+38", "Pancerz obuchowe": "+38", "Pancerz kłute": "+39"}},
    "Virveny": {"rank": 7, "cap": 15, "slots": 2, "type": "Buty", "stats": {"Waga": "20", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana zręczność": "75", "Siła": "+7", "Zręczność": "+9", "PŻ": "+150", "Mana": "+50", "Kondycja": "+150", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+38", "Pancerz kłute": "+36", "Odporność ogień": "+15"}},
    "Fanga": {"rank": 7, "cap": 15, "slots": 2, "type": "Kastety", "stats": {"Waga": "15", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana zręczność": "75", "Obrażenia": "179", "Typ obrażeń": "Obuchowe", "Siła": "+10", "Zręczność": "+33", "PŻ": "+130", "Mana": "+90", "Kondycja": "+100"}},
    "Griv": {"rank": 7, "cap": 15, "slots": 2, "type": "Pierścień", "stats": {"Waga": "1", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "PŻ": "+550", "Mana": "+100", "Kondycja": "+100"}},
    "Vogurun": {"rank": 7, "cap": 15, "slots": 2, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana moc": "75", "Moc": "+38", "Wiedza": "+37"}},
    "Yurugu": {"rank": 7, "cap": 15, "slots": 2, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana siła": "75", "Siła": "+38", "Zręczność": "+37"}},
    "Zadry": {"rank": 7, "cap": 15, "slots": 2, "type": "Rękawice", "stats": {"Waga": "6", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana zręczność": "75", "Siła": "+25", "Zręczność": "+28", "PŻ": "+180", "Kondycja": "+40"}},
    "Harttraum": {"rank": 7, "cap": 15, "slots": 2, "type": "Zbroja", "stats": {"Waga": "45", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana zręczność": "75", "Siła": "+16", "Zręczność": "+26", "PŻ": "+120", "Kondycja": "+30", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+35", "Pancerz kłute": "+35"}},
    "Otwieracz": {"rank": 7, "cap": 15, "slots": 2, "type": "Miecz", "stats": {"Waga": "24", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana siła": "75", "Obrażenia": "150", "Typ obrażeń": "Sieczne", "Siła": "+13", "Zręczność": "+11", "PŻ": "+300", "Mana": "+30", "Kondycja": "+180"}},
    "Sigil": {"rank": 7, "cap": 15, "slots": 2, "type": "Hełm", "stats": {"Waga": "18", "Wartość": "2 700 000 złota", "Wymagany poziom": "75", "Wymagana wiedza": "75", "Moc": "+10", "Wiedza": "+13", "PŻ": "+180", "Mana": "+130", "Pancerz sieczne": "+31", "Pancerz obuchowe": "+32", "Pancerz kłute": "+31", "Odporność energia": "+25"}},
    "Aquariusy": {"rank": 8, "cap": 18, "slots": 2, "type": "Spodnie", "stats": {"Waga": "32", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana zręczność": "85", "Siła": "+8", "Zręczność": "+25", "PŻ": "+250", "Kondycja": "+80", "Pancerz sieczne": "+36", "Pancerz obuchowe": "+36", "Pancerz kłute": "+36"}},
    "Aqueniry": {"rank": 8, "cap": 18, "slots": 2, "type": "Buty", "stats": {"Waga": "12", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana wiedza": "85", "Moc": "+19", "Wiedza": "+30", "PŻ": "+150", "Mana": "+20", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+37", "Pancerz kłute": "+35"}},
    "Nurt": {"rank": 8, "cap": 18, "slots": 2, "type": "Pas", "stats": {"Waga": "13", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana zręczność": "85", "Siła": "+19", "Zręczność": "+38", "PŻ": "+200", "Mana": "+20", "Kondycja": "+60"}},
    "Tsunami": {"rank": 8, "cap": 18, "slots": 2, "type": "Peleryna", "stats": {"Waga": "16", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana wiedza": "85", "Moc": "+8", "Wiedza": "+35", "PŻ": "+250", "Mana": "+170"}},
    "Batagur": {"rank": 7, "cap": 15, "slots": 2, "type": "Młot dwuręczny", "stats": {"Waga": "40", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana siła": "85", "Obrażenia": "217", "Typ obrażeń": "Obuchowe", "Siła": "+47", "Zręczność": "+10", "PŻ": "+80", "Kondycja": "+200"}},
    "Karapaks": {"rank": 8, "cap": 18, "slots": 2, "type": "Tarcza", "stats": {"Waga": "35", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana zręczność": "85", "Wymagana klasa": "Rycerz", "Siła": "+9", "Zręczność": "+11", "PŻ": "+200", "Mana": "+10", "Kondycja": "+200", "Pancerz sieczne": "+40", "Pancerz obuchowe": "+40", "Pancerz kłute": "+40"}},
    "Mauremys": {"rank": 8, "cap": 18, "slots": 2, "type": "Pierścień", "stats": {"Waga": "3", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana moc": "85", "Moc": "+38", "Wiedza": "+32", "PŻ": "+100", "Mana": "+50"}},
    "Gjolmar": {"rank": 7, "cap": 15, "slots": 2, "type": "Łuk", "stats": {"Waga": "15", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana zręczność": "85", "Obrażenia": "196", "Typ obrażeń": "Kłute", "Siła": "+20", "Zręczność": "+40", "PŻ": "+150", "Mana": "+50", "Kondycja": "+50"}},
    "Skiilfy": {"rank": 8, "cap": 18, "slots": 2, "type": "Spodnie", "stats": {"Waga": "14", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana wiedza": "85", "Moc": "+22", "Wiedza": "+25", "PŻ": "+150", "Mana": "+50", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+35", "Pancerz kłute": "+35"}},
    "Skogan": {"rank": 8, "cap": 18, "slots": 2, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "4 900 000 złota", "Wymagany poziom": "85", "Wymagana siła": "85", "Siła": "+44", "Zręczność": "+25", "PŻ": "+120", "Mana": "+20", "Kondycja": "+20"}},
    "Exuvium": {"rank": 8, "cap": 18, "slots": 2, "type": "Pas", "stats": {"Waga": "12", "Wartość": "6 600 000 złota", "Wymagany poziom": "90", "Wymagana wiedza": "90", "Moc": "+5", "Wiedza": "+40", "PŻ": "+350", "Mana": "+100"}},
    "Pazury": {"rank": 8, "cap": 18, "slots": 2, "type": "Rękawice", "stats": {"Waga": "10", "Wartość": "6 600 000 złota", "Wymagany poziom": "90", "Wymagana wiedza": "90", "Moc": "+22", "Wiedza": "+24", "PŻ": "+120", "Mana": "+320"}},
    "Pysk": {"rank": 8, "cap": 18, "slots": 2, "type": "Hełm", "stats": {"Waga": "19", "Wartość": "6 600 000 złota", "Wymagany poziom": "90", "Wymagana siła": "90", "Siła": "+26", "Zręczność": "+23", "PŻ": "+180", "Kondycja": "+50", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+35", "Pancerz kłute": "+35"}},
    "Rozdzieracz Światów": {"rank": 8, "cap": 18, "slots": 2, "type": "Topór dwuręczny", "stats": {"Waga": "25", "Wartość": "8 300 000 złota", "Wymagany poziom": "95", "Wymagana zręczność": "95", "Obrażenia": "227", "Typ obrażeń": "Sieczne", "Siła": "+27", "Zręczność": "+35", "PŻ": "+180", "Kondycja": "+150"}},
    "Scornaxy": {"rank": 8, "cap": 18, "slots": 2, "type": "Karwasze", "stats": {"Waga": "5", "Wartość": "6 600 000 złota", "Wymagany poziom": "90", "Wymagana moc": "90", "Moc": "+28", "Wiedza": "+17", "PŻ": "+270", "Mana": "+180"}},
    "Furiony": {"rank": 8, "cap": 18, "slots": 2, "type": "Karwasze", "stats": {"Waga": "5", "Wartość": "6 600 000 złota", "Wymagany poziom": "90", "Wymagana siła": "90", "Siła": "+28", "Zręczność": "+17", "PŻ": "+320", "Kondycja": "+130"}},
    "Hvariony": {"rank": 8, "cap": 18, "slots": 2, "type": "Rękawice", "stats": {"Waga": "12", "Wartość": "8 300 000 złota", "Wymagany poziom": "95", "Wymagana siła": "95", "Siła": "+34", "Zręczność": "+24", "PŻ": "+250", "Mana": "+20", "Kondycja": "+100"}},
    "Angwallion": {"rank": 9, "cap": 21, "slots": 2, "type": "Peleryna", "stats": {"Waga": "24", "Wartość": "10 000 000 złota", "Wymagany poziom": "100", "Wymagana zręczność": "100", "Siła": "+12", "Zręczność": "+30", "PŻ": "+200", "Mana": "+100", "Kondycja": "+100", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Dmorlung": {"rank": 8, "cap": 18, "slots": 2, "type": "Zbroja", "stats": {"Waga": "20", "Wartość": "8 300 000 złota", "Wymagany poziom": "95", "Wymagana siła": "95", "Siła": "+19", "Zręczność": "+18", "PŻ": "+200", "Kondycja": "+100", "Pancerz sieczne": "+38", "Pancerz obuchowe": "+38", "Pancerz kłute": "+38", "Odporność zimno": "+15"}},
    "Htagan": {"rank": 9, "cap": 21, "slots": 2, "type": "Hełm", "stats": {"Waga": "18", "Wartość": "10 000 000 złota", "Wymagany poziom": "100", "Wymagana moc": "100", "Moc": "+25", "Wiedza": "+24", "PŻ": "+250", "Mana": "+50", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+35", "Pancerz kłute": "+35", "Odporność uroki": "+10"}},
    "Vorleah": {"rank": 8, "cap": 18, "slots": 2, "type": "Zbroja", "stats": {"Waga": "20", "Wartość": "8 300 000 złota", "Wymagany poziom": "95", "Wymagana wiedza": "95", "Moc": "+16", "Wiedza": "+25", "PŻ": "+200", "Mana": "+100", "Kondycja": "+20", "Pancerz sieczne": "+35", "Pancerz obuchowe": "+35", "Pancerz kłute": "+35", "Odporność zimno": "+15"}},
    "Envile": {"rank": 10, "cap": 24, "slots": 3, "type": "Buty", "stats": {"Waga": "17", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana moc": "110", "Moc": "+50", "Wiedza": "+39", "PŻ": "+140", "Mana": "+60", "Pancerz sieczne": "+30", "Pancerz obuchowe": "+30", "Pancerz kłute": "+30"}},
    "Nienawiść Draugula": {"rank": 10, "cap": 24, "slots": 3, "type": "Pas", "stats": {"Waga": "8", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana siła": "110", "Siła": "+63", "Zręczność": "+42", "PŻ": "+120", "Kondycja": "+40"}},
    "Przysięga Draugula": {"rank": 10, "cap": 24, "slots": 3, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana moc": "110", "Moc": "+50", "Wiedza": "+50", "PŻ": "+110", "Mana": "+60", "Kondycja": "+40"}},
    "Zagłada Ludów": {"rank": 10, "cap": 24, "slots": 3, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana siła": "110", "Siła": "+50", "Zręczność": "+50", "PŻ": "+110", "Mana": "+40", "Kondycja": "+60"}},
    "Alendry": {"rank": 10, "cap": 24, "slots": 3, "type": "Buty", "stats": {"Waga": "16", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana wiedza": "110", "Moc": "+16", "Wiedza": "+43", "PŻ": "+200", "Mana": "+40", "Pancerz sieczne": "+37", "Pancerz obuchowe": "+37", "Pancerz kłute": "+37", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Erbaile": {"rank": 10, "cap": 24, "slots": 3, "type": "Spodnie", "stats": {"Waga": "21", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana zręczność": "110", "Siła": "+11", "Zręczność": "+33", "PŻ": "+220", "Kondycja": "+130", "Pancerz sieczne": "+40", "Pancerz obuchowe": "+40", "Pancerz kłute": "+40", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Szpony": {"rank": 10, "cap": 24, "slots": 3, "type": "Kastety", "stats": {"Waga": "10", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana zręczność": "110", "Obrażenia": "239", "Typ obrażeń": "Sieczne", "Siła": "+19", "Zręczność": "+48", "PŻ": "+250", "Mana": "+200", "Kondycja": "+90"}},
    "Taehal": {"rank": 10, "cap": 24, "slots": 3, "type": "Łuk", "stats": {"Waga": "15", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana zręczność": "110", "Obrażenia": "239", "Typ obrażeń": "Kłute", "Siła": "+18", "Zręczność": "+51", "PŻ": "+300", "Mana": "+90", "Kondycja": "+130"}},
    "Ariarchy": {"rank": 10, "cap": 24, "slots": 3, "type": "Karwasze", "stats": {"Waga": "5", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana moc": "110", "Moc": "+45", "Wiedza": "+43", "PŻ": "+80", "Mana": "+200", "Kondycja": "+50"}},
    "Groza Seleny": {"rank": 10, "cap": 24, "slots": 3, "type": "Pas", "stats": {"Waga": "3", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana zręczność": "110", "Siła": "+16", "Zręczność": "+55", "PŻ": "+230", "Mana": "+20", "Kondycja": "+70", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Hańba Seleny": {"rank": 10, "cap": 24, "slots": 3, "type": "Peleryna", "stats": {"Waga": "14", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana wiedza": "110", "Moc": "+17", "Wiedza": "+40", "PŻ": "+280", "Mana": "+180", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Mallus Selenorum": {"rank": 10, "cap": 24, "slots": 3, "type": "Topór", "stats": {"Waga": "40", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana siła": "110", "Obrażenia": "211", "Typ obrażeń": "Sieczne", "Siła": "+26", "Zręczność": "+20", "PŻ": "+400", "Mana": "+100", "Kondycja": "+250"}},
    "Serce Seleny": {"rank": 10, "cap": 24, "slots": 3, "type": "Naszyjnik", "stats": {"Waga": "3", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "PŻ": "+350", "Mana": "+100", "Kondycja": "+100", "Odporność ogień": "+55", "Odporność zimno": "+55", "Odporność energia": "+55", "Odporność uroki": "+55"}},
    "Unduriusy": {"rank": 10, "cap": 24, "slots": 3, "type": "Karwasze", "stats": {"Waga": "5", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana siła": "110", "Siła": "+53", "Zręczność": "+43", "PŻ": "+90", "Mana": "+40", "Kondycja": "+120"}},
    "Admiralski Gronostaj": {"rank": 10, "cap": 24, "slots": 3, "type": "Peleryna", "stats": {"Waga": "15", "Wartość": "28 750 000 złota", "Wymagany poziom": "115", "Wymagana zręczność": "115", "Siła": "+35", "Zręczność": "+45", "PŻ": "+300", "Mana": "+80", "Kondycja": "+140"}},
    "Inavoxy": {"rank": 10, "cap": 24, "slots": 3, "type": "Karwasze", "stats": {"Waga": "5", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana wiedza": "110", "Moc": "+10", "Wiedza": "+25", "PŻ": "+700", "Mana": "+110", "Kondycja": "+50"}},
    "Kil": {"rank": 10, "cap": 24, "slots": 3, "type": "Tarcza", "stats": {"Waga": "35", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana zręczność": "110", "Wymagana klasa": "Rycerz", "Siła": "+20", "Zręczność": "+26", "PŻ": "+280", "Mana": "+80", "Kondycja": "+150", "Pancerz sieczne": "+40", "Pancerz obuchowe": "+40", "Pancerz kłute": "+40"}},
    "Szpony Seimhi": {"rank": 10, "cap": 24, "slots": 3, "type": "Rękawice", "stats": {"Waga": "12", "Wartość": "28 750 000 złota", "Wymagany poziom": "115", "Wymagana wiedza": "115", "Moc": "+28", "Wiedza": "+45", "PŻ": "+300", "Mana": "+240", "Kondycja": "+50"}},
    "Takerony": {"rank": 10, "cap": 24, "slots": 3, "type": "Karwasze", "stats": {"Waga": "5", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana zręczność": "110", "Siła": "+10", "Zręczność": "+25", "PŻ": "+700", "Mana": "+50", "Kondycja": "+110"}},
    "Trójząb Admiralski": {"rank": 10, "cap": 24, "slots": 3, "type": "Kije", "stats": {"Waga": "18", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana moc": "110", "Obrażenia": "239", "Typ obrażeń": "Obuchowe", "Moc": "+65", "Wiedza": "+34", "PŻ": "+140", "Mana": "+50", "Kondycja": "+30"}},
    "Ból": {"rank": 10, "cap": 24, "slots": 3, "type": "Kije", "stats": {"Waga": "5", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana wiedza": "110", "Obrażenia": "239", "Typ obrażeń": "Kłute", "Moc": "+21", "Wiedza": "+40", "PŻ": "+400", "Mana": "+150", "Kondycja": "+50"}},
    "Cierń": {"rank": 10, "cap": 24, "slots": 3, "type": "Miecz dwuręczny", "stats": {"Waga": "30", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana siła": "110", "Obrażenia": "266", "Typ obrażeń": "Sieczne", "Siła": "+50", "Zręczność": "+30", "PŻ": "+250", "Kondycja": "+160"}},
    "Cierpiętniki": {"rank": 10, "cap": 24, "slots": 3, "type": "Buty", "stats": {"Waga": "19", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana siła": "110", "Siła": "+49", "Zręczność": "+31", "PŻ": "+120", "Kondycja": "+50", "Pancerz sieczne": "+40", "Pancerz obuchowe": "+40", "Pancerz kłute": "+40"}},
    "Udręki": {"rank": 10, "cap": 24, "slots": 3, "type": "Spodnie", "stats": {"Waga": "15", "Wartość": "22 500 000 złota", "Wymagany poziom": "110", "Wymagana moc": "110", "Moc": "+44", "Wiedza": "+36", "PŻ": "+80", "Mana": "+100", "Pancerz sieczne": "+39", "Pancerz obuchowe": "+39", "Pancerz kłute": "+39"}},
    "Aeterus Passio": {"rank": 10, "cap": 24, "slots": 3, "type": "Rękawice", "stats": {"Waga": "18", "Wartość": "28 750 000 złota", "Wymagany poziom": "115", "Wymagana zręczność": "115", "Siła": "+40", "Zręczność": "+45", "PŻ": "+300", "Mana": "+20", "Kondycja": "+60", "Odporność zimno": "+20", "Odporność uroki": "+10"}},
    "Miłość Morany": {"rank": 10, "cap": 24, "slots": 3, "type": "Hełm", "stats": {"Waga": "15", "Wartość": "35 000 000 złota", "Wymagany poziom": "120", "Wymagana moc": "120", "Moc": "+27", "Wiedza": "+25", "PŻ": "+340", "Mana": "+100", "Pancerz sieczne": "+40", "Pancerz obuchowe": "+40", "Pancerz kłute": "+40", "Odporność ogień": "+20", "Odporność zimno": "+20", "Odporność energia": "+20", "Odporność uroki": "+20"}},
    "Objęcia Morany": {"rank": 10, "cap": 24, "slots": 3, "type": "Pas", "stats": {"Waga": "7", "Wartość": "28 750 000 złota", "Wymagany poziom": "115", "Wymagana wiedza": "115", "Moc": "+40", "Wiedza": "+45", "PŻ": "+280", "Mana": "+80", "Kondycja": "+20", "Odporność zimno": "+20", "Odporność uroki": "+10"}},
    "Pamięć Morany": {"rank": 10, "cap": 24, "slots": 3, "type": "Hełm", "stats": {"Waga": "15", "Wartość": "35 000 000 złota", "Wymagany poziom": "120", "Wymagana siła": "120", "Siła": "+29", "Zręczność": "+25", "PŻ": "+300", "Kondycja": "+120", "Pancerz sieczne": "+45", "Pancerz obuchowe": "+45", "Pancerz kłute": "+45", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Arhauty": {"rank": 11, "cap": 28, "slots": 3, "type": "Buty", "stats": {"Waga": "21", "Wartość": "50 750 000 złota", "Wymagany poziom": "127", "Wymagana siła": "50", "Wymagana zręczność": "50", "Zręczność": "+25", "PŻ": "+750", "Kondycja": "+70", "Pancerz sieczne": "+50", "Pancerz obuchowe": "+50", "Pancerz kłute": "+50", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Dorbis": {"rank": 11, "cap": 28, "slots": 3, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "50 750 000 złota", "Wymagany poziom": "127", "Wymagana zręczność": "125", "Siła": "+45", "Zręczność": "+53", "PŻ": "+310", "Mana": "+30", "Kondycja": "+170", "Odporność ogień": "+10", "Odporność energia": "+30"}},
    "Ortasis": {"rank": 11, "cap": 28, "slots": 3, "type": "Naszyjnik", "stats": {"Waga": "2", "Wartość": "50 750 000 złota", "Wymagany poziom": "127", "Wymagana wiedza": "125", "Moc": "+40", "Wiedza": "+58", "PŻ": "+310", "Mana": "+170", "Kondycja": "+30", "Odporność ogień": "+10", "Odporność energia": "+30"}},
    "Temary": {"rank": 11, "cap": 28, "slots": 3, "type": "Spodnie", "stats": {"Waga": "19", "Wartość": "50 750 000 złota", "Wymagany poziom": "127", "Wymagana moc": "50", "Wymagana wiedza": "50", "Wiedza": "+25", "PŻ": "+750", "Mana": "+70", "Pancerz sieczne": "+45", "Pancerz obuchowe": "+45", "Pancerz kłute": "+45", "Odporność ogień": "+20", "Odporność zimno": "+20", "Odporność energia": "+20", "Odporność uroki": "+20"}},
    "Cień Tarula": {"rank": 11, "cap": 28, "slots": 3, "type": "Peleryna", "stats": {"Waga": "8", "Wartość": "57 500 000 złota", "Wymagany poziom": "130", "Wymagana moc": "130", "Moc": "+68", "Wiedza": "+63", "PŻ": "+120", "Mana": "+150", "Kondycja": "+20", "Odporność ogień": "+15", "Odporność energia": "+15"}},
    "Salmurn": {"rank": 12, "cap": 32, "slots": 3, "type": "Zbroja", "stats": {"Waga": "25", "Wartość": "68 750 000 złota", "Wymagany poziom": "135", "Wymagana siła": "50", "Wymagana zręczność": "50", "Siła": "+22", "Zręczność": "+48", "PŻ": "+400", "Mana": "+80", "Kondycja": "+100", "Pancerz sieczne": "+50", "Pancerz obuchowe": "+50", "Pancerz kłute": "+50", "Odporność ogień": "+15", "Odporność zimno": "+15", "Odporność energia": "+15", "Odporność uroki": "+15"}},
    "Zalla": {"rank": 12, "cap": 32, "slots": 3, "type": "Zbroja", "stats": {"Waga": "22", "Wartość": "68 750 000 złota", "Wymagany poziom": "135", "Wymagana moc": "50", "Wymagana wiedza": "50", "Moc": "+24", "Wiedza": "+46", "PŻ": "+400", "Mana": "+130", "Kondycja": "+50", "Pancerz sieczne": "+45", "Pancerz obuchowe": "+45", "Pancerz kłute": "+45", "Odporność ogień": "+20", "Odporność zimno": "+20", "Odporność energia": "+20", "Odporność uroki": "+20"}},
    "Ziraki": {"rank": 11, "cap": 28, "slots": 3, "type": "Spodnie", "stats": {"Waga": "17", "Wartość": "57 500 000 złota", "Wymagany poziom": "130", "Wymagana siła": "130", "Siła": "+63", "Zręczność": "+55", "PŻ": "+140", "Kondycja": "+60", "Pancerz sieczne": "+38", "Pancerz obuchowe": "+38", "Pancerz kłute": "+38", "Odporność ogień": "+15", "Odporność energia": "+15"}},
    "Dar Skrzydlatej": {"rank": 12, "cap": 32, "slots": 3, "type": "Pierścień", "stats": {"Waga": "2", "Wartość": "80 000 000 złota", "Wymagany poziom": "140", "Zręczność": "+30", "Wiedza": "+30", "PŻ": "+640", "Mana": "+150", "Kondycja": "+150", "Odporność ogień": "+60", "Odporność zimno": "+60", "Odporność energia": "+60", "Odporność uroki": "+60", "Wzmocnienie drifów": "+15%"}},
    "Remigesy": {"rank": 12, "cap": 32, "slots": 3, "type": "Rękawice", "stats": {"Waga": "15", "Wartość": "68 750 000 złota", "Wymagany poziom": "135", "Wymagana zręczność": "135", "Siła": "+58", "Zręczność": "+70", "PŻ": "+300", "Mana": "+60", "Kondycja": "+90", "Odporność ogień": "+15", "Odporność energia": "+15", "Wzmocnienie drifów": "+15%"}},
    "Vengur": {"rank": 12, "cap": 32, "slots": 3, "type": "Peleryna", "stats": {"Waga": "12", "Wartość": "68 750 000 złota", "Wymagany poziom": "135", "Wymagana siła": "135", "Siła": "+68", "Zręczność": "+56", "PŻ": "+340", "Mana": "+30", "Kondycja": "+120", "Odporność zimno": "+15", "Odporność uroki": "+15", "Wzmocnienie drifów": "+15%"}},
    "Voglery": {"rank": 12, "cap": 32, "slots": 3, "type": "Rękawice", "stats": {"Waga": "15", "Wartość": "68 750 000 złota", "Wymagany poziom": "135", "Wymagana moc": "135", "Moc": "+74", "Wiedza": "+54", "PŻ": "+300", "Mana": "+110", "Kondycja": "+40", "Odporność zimno": "+15", "Odporność uroki": "+15", "Wzmocnienie drifów": "+15%"}},
    "Wyrok Hellara": {"rank": 12, "cap": 32, "slots": 3, "type": "Pas", "stats": {"Waga": "8", "Wartość": "68 750 000 złota", "Wymagany poziom": "135", "Wymagana wiedza": "135", "Moc": "+52", "Wiedza": "+72", "PŻ": "+280", "Mana": "+170", "Kondycja": "+40", "Odporność ogień": "+15", "Odporność energia": "+15", "Wzmocnienie drifów": "+15%"}},
    
    "Allenor": {"rank": 9, "cap": 25, "slots": 2, "type": "Miecz", "fixed_driffs": ["astah", "band"], "stats": {"Waga": "15", "Wartość": "3 000 000 złota", "Wymagany poziom": "60", "Wymagana klasa": "Rycerz", "Obrażenia": "100+lvl", "Typ obrażeń": "Sieczne", "Siła": "+15", "Zręczność": "+15", "PŻ": "+250", "Kondycja": "+50", "Modyfikator obrażeń fizycznych": "2%+0,5% co poziom", "Szansa na trafienie krytyczne": "2%+0,5% co poziom", "Dodatkowe PA": "1", "Wzmocnienie drifów": "+60%"}},
    "Attawa": {"rank": 9, "cap": 25, "slots": 2, "type": "Kije", "fixed_driffs": ["band", "oda"], "stats": {"Waga": "15", "Wartość": "3 000 000 złota", "Wymagany poziom": "60", "Wymagana klasa": "Voodoo", "Obrażenia": "120+lvl", "Typ obrażeń": "Obuchowe", "Moc": "+15", "Wiedza": "+30", "PŻ": "+100", "Mana": "+50", "Szansa na trafienie krytyczne": "2%+0,5% co poziom", "Modyfikator trafień mentalnych": "4%+1% co poziom", "Dodatkowe PA": "1", "Wzmocnienie drifów": "+60%"}},
    "Gorthdar": {"rank": 9, "cap": 25, "slots": 2, "type": "Topór dwuręczny", "fixed_driffs": ["unn", "band"], "stats": {"Waga": "15", "Wartość": "3 000 000 złota", "Wymagany poziom": "60", "Wymagana klasa": "Barbarzyńca", "Obrażenia": "130+lvl", "Typ obrażeń": "Sieczne", "Siła": "+25", "Zręczność": "+15", "PŻ": "+150", "Kondycja": "+50", "Dodatkowe obrażenia od ognia": "1,4%+0,35% co poziom", "Szansa na trafienie krytyczne": "2%+0,5% co poziom", "Dodatkowe PA": "1", "Wzmocnienie drifów": "+60%"}},
    "Imisindo": {"rank": 9, "cap": 25, "slots": 2, "type": "Łuk", "fixed_driffs": ["band", "ling"], "stats": {"Waga": "15", "Wartość": "3 000 000 złota", "Wymagany poziom": "60", "Wymagana klasa": "Łucznik", "Obrażenia": "105+lvl", "Typ obrażeń": "Kłute", "Siła": "+15", "Zręczność": "+20", "PŻ": "+200", "Kondycja": "+50", "Szansa na trafienie krytyczne": "2%+0,5% co poziom", "Modyfikator trafień dystansowych": "4%+1% co poziom", "Dodatkowe PA": "1", "Wzmocnienie drifów": "+60%"}},
    "Latarnia Życia": {"rank": 9, "cap": 25, "slots": 2, "type": "Kije", "fixed_driffs": ["err", "band"], "stats": {"Waga": "15", "Wartość": "3 000 000 złota", "Wymagany poziom": "60", "Wymagana klasa": "Druid", "Obrażenia": "120+lvl", "Typ obrażeń": "Obuchowe", "Moc": "+20", "Wiedza": "+25", "PŻ": "+100", "Mana": "+50", "Wyssanie many": "2%+0,5% co poziom", "Szansa na trafienie krytyczne": "2%+0,5% co poziom", "Dodatkowe PA": "1", "Wzmocnienie drifów": "+60%"}},
    "Washi": {"rank": 9, "cap": 25, "slots": 2, "type": "Kastety", "fixed_driffs": ["band", "ulk"], "stats": {"Waga": "15", "Wartość": "3 000 000 złota", "Wymagany poziom": "60", "Wymagana klasa": "Sheed", "Obrażenia": "115+lvl", "Typ obrażeń": "Kłute", "Siła": "+15", "Zręczność": "+20", "PŻ": "+200", "Kondycja": "+50", "Szansa na trafienie krytyczne": "2%+0,5% co poziom", "Modyfikator trafień wręcz": "4%+1% co poziom", "Dodatkowe PA": "1", "Wzmocnienie drifów": "+60%"}},
    "Żmij": {"rank": 9, "cap": 25, "slots": 2, "type": "Kije", "fixed_driffs": ["band", "teld"], "stats": {"Waga": "15", "Wartość": "3 000 000 złota", "Wymagany poziom": "60", "Wymagana klasa": "Mag Ognia", "Obrażenia": "120+lvl", "Typ obrażeń": "Obuchowe", "Moc": "+30", "Wiedza": "+15", "PŻ": "+150", "Szansa na trafienie krytyczne": "2%+0,5% co poziom", "Szansa na podwójny atak": "2%+0,5% co poziom", "Dodatkowe PA": "1", "Wzmocnienie drifów": "+60%"}}
}

SLOT_MAPPING = {
    "head": ["Hełm"], 
    "neck": ["Naszyjnik", "Amulety"], 
    "gloves": ["Rękawice"], 
    "ring1": ["Pierścień"], 
    "ring2": ["Pierścień"], 
    "bracers": ["Karwasze", "Tarcza", "Tarcze"], 
    "boots": ["Buty"], 
    "weapon": ["Broń", "Miecz", "Miecz dwuręczny", "Miecz 2H", "Laska", "Łuk", "Topór", "Topór dwuręczny", "Topór 2H", "Młot", "Młot dwuręczny", "Młot jednoręczny", "Młot 2H", "Kastety", "Kije"],
    "legs": ["Spodnie"], 
    "waist": ["Pas", "Pasy"], 
    "body": ["Zbroja", "Zbroje"], 
    "cape": ["Peleryna", "Płaszcze"]
}

def find_image_file(item_name):
    if item_name in MANUAL_FILENAME_FIXES:
        fname = MANUAL_FILENAME_FIXES[item_name]
        for f in ['epik', 'rary']:
            if os.path.exists(os.path.join(app.root_path, 'static', f, fname)):
                return fname, f
        return fname, "rary"

    target = item_name.lower().replace(" ", "").replace("'", "").replace("-", "")
    for folder in ['epik', 'rary']:
        img_dir = os.path.join(app.root_path, 'static', folder)
        if not os.path.exists(img_dir): continue
        for filename in os.listdir(img_dir):
            name_no_ext = os.path.splitext(filename)[0]
            cleaned_file = name_no_ext.lower().replace(" ", "").replace("_", "").replace("'", "").replace("-", "")
            if target == cleaned_file or (len(target) > 3 and target in cleaned_file):
                return filename, folder
    return "default.png", "rary"

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/get_items/<slot_id>')
def get_items_list(slot_id):
    valid_types = SLOT_MAPPING.get(slot_id, [])
    result = {}
    for name, data in ITEMS_DB.items():
        if data['type'] in valid_types or data['type'] + "e" in valid_types or data['type'] + "y" in valid_types:
            real_filename, folder_name = find_image_file(name)
            item_data = data.copy()
            item_data['img'] = real_filename
            item_data['folder'] = folder_name
            result[name] = item_data
    return jsonify(result)

if __name__ == '__main__':
    app.run(debug=True)